package team.a501.rif.domain.achievement;

public enum AchievementTag {
    RIF_FIRST_USE,
    PLASTIC_SUCCESS_FIRST,
    PLASTIC_SUCCESS_FIVE_TIMES,
    PLASTIC_SUCCESS_TEN_TIMES,
    RECYCLE_SUCCESS_FIRST,
    RECYCLE_SUCCESS_FIVE_TIMES,
    RECYCLE_SUCCESS_TEN_TIMES,
    RIF_PERFECT_FIRST,
    RIF_PERFECT_FIVE_TIMES
}
